### ISSUE TITLE
正文引用图后面也必须要空格吗，看起来好丑

### ISSUE THREAD

**Issue by xsro** [dhiyu/NJUPT-Bachelor#2]
<img width="675" alt="截屏2022-05-03 下午7 13 50" src="https://user-images.githubusercontent.com/64292434/166443598-fec7f965-686d-47cf-9fd1-ccbfeca15582.png">

**Comment by dhiyu** [comment]
我在README.md中有提到这个问题，如图：
![image](https://user-images.githubusercontent.com/37993729/166471693-4294ff05-8454-4c10-86de-27885b980bb9.png)
我当时因为时间问题，所以临时的解决办法就是直接手动打了引用。

**Comment by dhiyu** [comment]
你可以尝试解决这个问题，并pull request给我，一起完善模板。

**Comment by xsro** [comment]
感谢前辈，我正在尝试，这个模板太棒了

**Comment by dhiyu** [comment]
2021届的word版本我有存，稍后我将它添加到项目中。另外我注意到你最新的request中编译的pdf文件标题字体好像没有加粗，我刚在本地重新编译，没有发现有问题，是否你的mac环境下模板存在一些问题？

**Comment by xsro** [comment]
感谢，我尽力排查一下，我打算最后还是用windows下编译，跨平台令人头秃

**Comment by dhiyu** [comment]
好的好的，windows系统下还是比较稳定一些，有问题再交流哈！

**Comment by xsro** [comment]
> 2021届的word版本我有存，稍后我将它添加到项目中。另外我注意到你最新的request中编译的pdf文件标题字体好像没有加粗，我刚在本地重新编译，没有发现有问题，是否你的mac环境下模板存在一些问题？

我猜测是我把cls中关于mac字体的部分修改为了mac系统自带的字体，但是这些字体并不完全合乎要求。
我修改回原来的设置并安装font文件夹中的字体后没有问题。

要不还是把这一部分改回去吧

```
git revert b5db6abffa37c4730ef4f063b42168cd80158c9d
```

**Comment by dhiyu** [comment]
已经回滚
