### ISSUE TITLE
后续毕设论文查重，格式是否会有问题？

### ISSUE THREAD

**Issue by ICraZY-EE** [dhiyu/NJUPT-Bachelor#5]
前辈，我是电院的，最近在做毕设，也想借机上手latex，但是我有些顾虑，例如最后查重如果提交PDF格式，和word格式相比查重结果会有差异吗？学校是否要求提供一份word版本论文定稿作为存档呢？
tex格式转docx有较为可靠的途径吗？(指图片公式字体以及排版等不变)

**Comment by dhiyu** [comment]
你好，根据我的经历：
1. 查重时侧重的是内容不是格式，可以复制文本到word里直接查重，或者部分查重网站可以直接提交文本；
2. 学校不会要求提供word存档，交pdf即可；
3. 据我所知没有比较可靠的途径，大部分是tex -> pdf -> word，还是比较混乱，不建议。

总结：使用latex应该是没有问题的。

**Comment by ICraZY-EE** [comment]
好的，感谢！
